### ISSUE TITLE
Multiple connection styles

### ISSUE THREAD

**Issue by Photon-Engineer** [retejs/rete#431]
Is it possible to apply different styles to the various connections based on some logic? Specifically such as what type of socket they are connected to, or what type of data the connection is associated with? 

For example, I'd like to have, say, a blue connection line for numeric data and a white connection line for string data.

I'm not sure if the render plugin makes a difference for this, but in case it does, I'm mostly using the react-render-plugin. 

Thank you, and great work!

**Comment by Hatead1** [comment]
https://gitter.im/retejs/Lobby - post dated 07 apr.

![links](https://user-images.githubusercontent.com/41296890/80379243-7e1d0080-88a6-11ea-9c4f-f067ce1ab7ec.jpg)

**Comment by Photon-Engineer** [comment]
I ended up finding a different way to do it using the renderconnection event to get access to the connection html element in the dom.

I think this way works better for me, but I appreciate your help. 

```js
this.editor.on('renderconnection', (connection) => {
            const key = connection.connection.output.key;
            const node = connection.connection.output.node;
            const type = node.outputs.get(key).socket.name; // Get the name of the socket output socket
            var connectionClass;
            if (type === "string") {
                connectionClass = "string-connection";
            }else if (type === "number") {
                connectionClass = "number-connection";
            }
            var c = connection.el.children;
            for (var i = 0; i < c.length; i++) {
                c[i].children[0].classList.add(connectionClass);
            }
        });
```

Then I just create the `string-connection` and `number-connection` styles with css.

**Comment by Hatead1** [comment]
I think there are a couple more ways we can do that.

**Comment by RemiRigal** [comment]
If you look at the render function of connections, it adds the socket type to the SVG container as classes:
https://github.com/retejs/connection-plugin/blob/7a4b68409982691ea14ab0018ca23d8d057e48b8/src/utils.ts#L36

So if you have two sockets `number` and `string` you can apply the following style:
```css
svg.connection.socket-input-number,
svg.connection.socket-output-number {
  path.main-path {
    stroke: blue;
  }
}

svg.connection.socket-input-string,
svg.connection.socket-output-string {
  path.main-path {
    stroke: red;
  }
}
```

And if you need a default style:
```css
svg.connection {
  path.main-path {
    stroke: gray;
  }
}
```

When dragging the connection, the default color will be used until connected though, I'm still trying to find a way to solve that without changing the library's code.
