### ISSUE TITLE
Angular: Add control / custom element in a connection.

### ISSUE THREAD

**Issue by mianfrigo** [retejs/rete#663]
im currently trying to add menu that will be display in the connection between two node when the user hover the connection.
![Screenshot from 2023-10-02 12-09-41](https://github.com/retejs/rete/assets/16882735/b4a4f899-305c-4712-88fb-9050c670c141)
Every time i try to add the component inside of the connection template i get this error` NG3003: Import cycles would need to be created to compile this component`. is there a way do this...?

**Comment by Ni55aN** [comment]
can you share some code or a reproducible example on Codesandbox?

**Comment by mianfrigo** [comment]
Ok i found the way to add the component to the custom connection, i follow the example labeled connections, but for reason i can no center the component. here is what i got so far:

**custom-connection.html**

```html
<svg data-testid="connection" #svg>
  <path [ngClass]="{ 'source-connected': !!data.source, 'target-connected': !!data.target }" [attr.d]="path" />
</svg>
<div class="connection-menu" #menu>
  <exb-node-menu
    [insertBetween]="true"
    [connectionId]="data.id"
    [editor]="data.editor"
    [area]="data.area"></exb-node-menu>
</div>
```

**custom-connection.ts**

```typescript
export class CustomConnectionComponent implements AfterViewInit {
  @Input() data!: CustomConnection;
  @Input() start: any;
  @Input() end: any;
  @Input() path!: string;
  @ViewChild('svg') connection!: ElementRef;
  @ViewChild('menu') menu!: ElementRef;

  constructor() {}

  ngAfterViewInit(): void {
    timer(0).subscribe(() => {
      this.positionMenu();
    });
  }

  positionMenu(): void {
    const path = this.connection.nativeElement.firstChild;
    const pathTotalLength = path.getTotalLength();
    console.log(pathTotalLength);
    const point = path.getPointAtLength(pathTotalLength / 2);
    this.menu.nativeElement.style.transform = `translate(${point.x}px, ${point.y}px)`;
  }
}

```

**custom-connection.scss**

```scss
svg {
  overflow: visible;
  position: absolute;
  pointer-events: none;
  width: 9999px;
  height: 9999px;
  path {
    fill: none;
    stroke-width: 1px;
    stroke: var(--moderate-border-color);
    pointer-events: auto;

    &.source-connected:not(.target-connected) {
      stroke: var(--purple-border-color);
      stroke-dasharray: 2 2;
    }
  }
}

.connection-menu {
  position: absolute;
  top: 0;
  left: 0;
}
```

this the current result i have:

![Screenshot from 2023-10-04 18-02-54](https://github.com/retejs/rete/assets/16882735/1694800e-43bb-430d-b26c-770a09c224a6)

and at the moment of drag the node the button element does not stick to the svg path element.
