### ISSUE TITLE
In the examples / Guides customized Paths are not explained very well. Plz add a tutorial for that.

### ISSUE THREAD

**Issue by pokecheater** [retejs/rete#727]
### Description

Hey Retejs- Team,

I have another question. 

I want to give my paths the same color as the socket color.
In the old version I was able to achieve that by an css rule since the connection was back then a child of the socket.

For example:

```css
 #api-designer ::v-deep(.socket.used.numpy > svg > path) {
      fill: #2d848a ;
  }
  #api-designer ::v-deep(.node .socket.numpy:not(.used) > svg > path) {
      fill: #2d848acc;
  }
  #api-designer ::v-deep(.node .socket.numpy:hover > svg > path) {
      fill: #2d848a;
  }
```
Now with the vue3 version things are not that easy anymore, since the path is now at the same stage as the socket and there is no possibility to get know to which socket the path belong.

So far I found out, that I have access to the path data inside the PathTemplate.

<img width="1562" alt="Image" src="https://github.com/user-attachments/assets/d4df963d-eb72-41c3-99bc-c4c9b8aee98c" />

but since there is no reference to editor I can not find out of which type (equals the name of the socket) the input and the output sockets are.

Do you have an idea how to achieve the color styling of the path or how to access the editor within the pathTemplate?

Thx in advance

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
